---
title: "Preprocessing"
output: html_notebook
---
```{r}
# load in data
data = read.csv("Airbnb_Data.csv",sep = ",",header = TRUE)

# dimensions of our dataset
print(dim(data))

# look at all variable names
print(colnames(data))

# filter for listings only in New York City
data = subset(data, city == 'NYC')

# remove id and thumbnail columns
data <- subset(data, select = -c(id, thumbnail_url))

# check the new dimensions
print(dim(data))

# count null in columns
print(colSums(is.na(data)))

# it looks like review score rating contains null values, we will replace those with "missing"
data$review_scores_rating[is.na(data$review_scores_rating)] <- "missing"

# Print the missing count to verify
cat("Count of 'missing' in review_scores_rating: ", sum(data$review_scores_rating == "missing"), "\n")

# convert columns to date format
data$first_review <- as.Date(data$first_review)
data$last_review <- as.Date(data$last_review)
data$host_since <- as.Date(data$host_since)

# create new column 'age' that is the time between last and first review
data$age <- as.numeric(data$last_review - data$first_review)

# check that calculation was applied correctly
head(data$age)

# create new column "hostAge" that is the time between last review and host since.
data$hostAge <- as.numeric(data$last_review - data$host_since)

# check the application
head(data$hostAge)

# create new column "review ratio" which will be (number_of_reviews / age), we can later modify this to a percent for readability
data$occupancyRatio <- (data$number_of_reviews / data$age)

# check that the calculation was applied correctly
head(data$occupancyRatio)
```
```{r}
# here we are going to work on counting how often each amenity occurs in the dataset

# split the amenities strings into lists of words/values
split_amenities <- strsplit(data$amenities, "[,]")

# combine all lists into one big list
all_amenities <- unlist(split_amenities)

# remove the curly braces and quotes
all_amenities <- gsub("[{}\"]", "", all_amenities)

# count the occurrences of each word/value
amenities_counts <- table(all_amenities)

# sort the counts in descending order
sorted_amenities_counts <- sort(amenities_counts, decreasing = TRUE)

# top 10 most common amenities
top10_amenities <- names(sorted_amenities_counts[1:10])
```

```{r}
# replace null values for beds, bedrooms, bathrooms, host response rate as well
data$beds[is.na(data$beds)] <- "missing"
data$bedrooms[is.na(data$bedrooms)] <- "missing"
data$bathrooms[is.na(data$bathrooms)] <- "missing"
data$host_response_rate[data$host_response_rate == ""] <- "missing"
# remove rows missing "first_review", etc
data <- na.omit(data)
# remove inf values in occupancyRatio
remove <- c()
for (i in 1:nrow(data)){
  if (is.infinite(data$occupancyRatio[i])){
    remove <- c(remove, i)
  }
}
data <- data[-remove, ]

# create columns for amenities
for (i in top10_amenities){
  data[[i]] <- numeric(nrow(data))
}
# 1 if amenity is listed; 0 otherwise
for (amenity in top10_amenities){
  for (row in 1:nrow(data)){
    amenities <- gsub("[{}\"]", "", data$amenities[row])
    if (grepl(amenity, amenities)){
      data[[amenity]][row] <- 1
    }
  }
}

data
write.csv(data, "cleaned_data.csv", row.names=FALSE)
```

